export const IS_AUTHORIZED = "IS_AUTHORIZED";
export const SET_USERS = "SET_USERS";
export const FETCH_USERS = "FETCH_USERS";
export const IS_FETCHING = "IS_FETCHING";
export const SET_CHOSEN_USER = "SET_CHOSEN_USER";
export const SET_CURRENT_PAGE_NUMBER = "SET_CURRENT_PAGE_NUMBER";
export const SET_PREVIOUS_PAGE_NUMBER = "SET_PREVIOUS_PAGE_NUMBER";
