export const IS_AUTHORIZED = "IS_AUTHORIZED";
export const SET_USERS = "SET_USERS";
export const FETCH_USERS = "FETCH_USERS";
export const IS_FETCHING = "IS_FETCHING";
export const SET_CHOSEN_USER = "SET_CHOSEN_USER";
export const RESET_CHOSEN_USER = "RESET_CHOSEN_USER";
export const SET_LOCAL_LANGUAGE = "SET_LOCAL_LANGUAGE";
export const DID_FETCHING_FAIL = "DID_FETCHING_FAIL";

